# French language

dSugg = {
	"bcp": "beaucoup",
    "ca": "ça",
    "cad": "c’est-à-dire",
    "càd": "c’est-à-dire",
    "cb": "combien|CB",
    "cdlt": "cordialement",
    "dc": "de|donc",
    "parce-que": "parce que",
    "pcq": "parce que",
    "pk": "pourquoi",
    "prq": "presque",
    "prsq": "presque",
    "pd": "pendant",
    "pdt": "pendant",
    "pdq": "pendant que",
    "pdtq": "pendant que",
    "pq": "pourquoi|PQ",
    "qcq": "quiconque",
    "qqch": "quelque chose",
    "qqn": "quelqu’un",
    "qqne": "quelqu’une",
    "qq": "quelque",
    "qqs": "quelques",
    "qquns": "quelques-uns",
    "qqunes": "quelques-unes",
    "ts": "tous",
    "tt": "tant|tout",
    "tte": "toute",
    "ttes": "toutes",
    "tq": "tant que|tandis que",
    "tdq": "tandis que",
    "y’a": "y a"
}
